CREATE TABLE IF NOT EXISTS public.other_operation_hires (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    base_lorry_number text not null,
    operation_name text not null,
    hire_date date not null,
    from_location text not null,
    to_location text not null,
    distance numeric not null default 0,
    first_100km_rate numeric not null default 0,
    rest_km_rate numeric not null default 0,
    fuel_litres numeric not null default 0,
    fuel_price_per_litre numeric not null default 0,
    fuel_cost numeric not null default 0,
    hire_amount numeric not null default 0,
    user_id uuid references auth.users(id) not null
);

ALTER TABLE public.other_operation_hires ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own other operation hires" ON public.other_operation_hires
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own other operation hires" ON public.other_operation_hires
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own other operation hires" ON public.other_operation_hires
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own other operation hires" ON public.other_operation_hires
    FOR DELETE USING (auth.uid() = user_id);
